export const refs = {
  categories: document.querySelector('.js-categories'),
  books: document.querySelector('.js-books'),
  modal: document.querySelector('.js-modal'),
  modalBook: document.querySelector('.js-modal-book'),
  closeModal: document.querySelector('.js-modal__close-btn'),
  addToCartBtn: document.querySelector('.js-modal-book__btn--cart'),
  addToWishlistBtn: document.querySelector('.js-modal-book__btn--wishlist'),
  cartBooksList: document.querySelector('.js-cart-books'),
  cartTotalPrice: document.querySelector('[data-price]'),
  cartCount: document.querySelector('[data-count]'),
  headerCartCount: document.querySelector('[data-cart-count]'),
  headerWishlistCount: document.querySelector('[data-wishlist-count]'),
  wishlist: document.querySelector('.js-wishlist-books'),
};
